

export const filterOptions = [
  { display: "Vegan", key: "vegan" },
  { display: "Carnivore", key: "eatsMeat" },
  { display: "Funny", key: "funny" },
  { display: "Honest", key: "honest" },
  { display: "Loves Drama", key: "lovesDrama" },
  { display: "Active", key: "active" },
  { display: "Considerate", key: "considerate" },
  { display: "Open communication", key: "openCommunication" },
  { display: "Loves to Party", key: "lovesToParty" },
  { display: "Splits the bill", key: "splitsTheBill" },
  { display: "Loves to cuddle", key: "lovesToCuddle" },
  { display: "5'9 and above", key: "tall" },
  { display: "Lives alone", key: "livesAlone" },
  { display: "Emotionally aware", key: "emotionallyAware" },
  { display: "Smokes", key: "smokes" },
  { display: "Likes to cook", key: "likesToCook" },
  { display: "Happy", key: "happy" },
  { display: "You are his priority", key: "priority" }
];


export const guys = [
  {
    id: 123,
    name: "Anixar",
    imageSrc:
      "./pics/Anixar.jpg",
    eatsMeat: false,
    vegan: true,
    funny: true,
    honest: true,
    lovesDrama: false,
    active: true,
    considerate: true,
    openCommunication: true,
    lovesToParty: false,
    splitsTheBill: false,
    lovesToCuddle: true,
    tall: true,
    livesAlone: true,
    emotionallyAware: true,
    smokes: false,
    likesToCook: true,
    happy: true,
    priority: true
  },
  {
     id: 124,
    name: "Evior",
    imageSrc:
      "./pics/Evior.jpg",
    eatsMeat: true,
    vegan: false,
    funny: true,
    honest: false,
    lovesDrama: false,
    active: true,
    considerate: true,
    openCommunication: false,
    lovesToParty: true,
    splitsTheBill: false,
    lovesToCuddle: true,
    tall: false,
    livesAlone: false,
    emotionallyAware: false,
    smokes: false,
    likesToCook: true,
    happy: true,
    priority: true
  },
  {
    id: 125,
    name: "Jorune",
    imageSrc:
      "./pics/Jorune.jpg",
    eatsMeat: true,
    vegan: false,
    funny: false,
    honest: false,
    lovesDrama: true,
    active: false,
    considerate: false,
    openCommunication: false,
    lovesToParty: true,
    splitsTheBill: true,
    lovesToCuddle: true,
    tall: false,
    livesAlone: false,
    emotionallyAware: false,
    smokes: true,
    likesToCook: false,
    happy: false,
    priority: false
  },
  {
    id: 126,
    name: "Ofeus",
    imageSrc:
      "./pics/Ofeus.jpg",
    eatsMeat: false,
    vegan: false,
    funny: true,
    honest: false,
    lovesDrama: false,
    active: true,
    considerate: true,
    openCommunication: false,
    lovesToParty: false,
    splitsTheBill: false,
    lovesToCuddle: true,
    tall: false,
    livesAlone: false,
    emotionallyAware: false,
    smokes: false,
    likesToCook: true,
    happy: true,
    priority: false
  },
  {
    id: 127,
    name: "Avotior",
    imageSrc:
      "./pics/Avotior.jpg",
    eatsMeat: true,
    vegan: false,
    funny: true,
    honest: false,
    lovesDrama: true,
    active: true,
    considerate: false,
    openCommunication: false,
    lovesToParty: true,
    splitsTheBill: false,
    lovesToCuddle: true,
    tall: false,
    livesAlone: true,
    emotionallyAware: false,
    smokes: false,
    likesToCook: false,
    happy: false,
    priority: true
  }
];
